// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufveeimuovazsviomvsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdmVlaW11b3ZhenN2aW9tdnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTkyMTksImV4cCI6MjA2MjQ3NTIxOX0.Ycc_M7i5pUBMCZW3qC9s2J_p_IgL7ZcRynehQ_ZgiJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);