import React from 'react';
import { Sparkles } from 'lucide-react';

interface AIQuickSummaryProps {
  carTitle: string;
  summary: string;
}

const AIQuickSummary: React.FC<AIQuickSummaryProps> = ({ carTitle, summary }) => {
  return (
    <div className="bg-neutral-8 rounded-xl p-6 mb-6">
      <div className="flex items-center gap-2 mb-4">
        <Sparkles className="w-5 h-5 text-motortrend-red" />
        <h3 className="typography-title text-neutral-1">AI Quick Summary</h3>
      </div>
      <p className="typography-body text-neutral-2 mb-4">{summary}</p>
      <p className="typography-caption text-neutral-3 italic">
        This summary was generated by AI using content from this MotorTrend article
      </p>
    </div>
  );
};

export default AIQuickSummary;
